---
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

env:
  TEST_TAG: eext:test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          # using recursive to avoid hardcoding paths
          # and missing any future additions
          recursive: true
          verbose: true

      - name: Lint yaml files
        run: yamllint .

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          # CentOS Stream 9 go  version
          go-version: '1.18.2'

      - name: Setup golint and gofmt
        run: |
          GO111MODULE=off go get -u golang.org/x/lint/golint

      - name: Run golint, go vet and go fmt
        run: |
          golint -set_exit_status ./...
          test -z $(gofmt -l .)
